INSERT INTO [OutputTables_Prod].[OutboundData] ([ProjectNumber_SKU]
      ,[Quantity]
      ,[ReceivedDate]
      ,[PickDate]
      ,[ShipDate]
      ,[Channel]
      ,[Velocity]
      ,[UnitsPerLineRange]
      ,[Weekday]
      ,[Week]
      ,[Weekday_Idx]
      ,[ProjectNumber_OrderNumber]
      ,[Date]
      ,[Week_Number]
      ,[LineCube]
      ,[LineWeight]
      ,[UnitOfMeasure]
      ,[BusinessUnit]
      ,[ShipContainerType]
      ,[SpecialHandlingCodes]
      ,[Carrier]
      ,[PickType])
VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?);