INSERT INTO [OutputTables_Prod].[Project] ([ProjectNumber]
    ,[Company]
    ,[Salesman]
    ,[Company Location]
    ,[Project Name]
    ,[Security Email]
    ,[Date Start]
    ,[DateForAnalysis]
    ,[WeekendDateRule]
    ,[Notes]
    ,[DataUploaded]
    ,[UploadDate]
    ,[ItemMasterFilePath]
    ,[InboundHeaderFilePath]
    ,[InboundDetailsFilePath]
    ,[InventoryFilePath]
    ,[OrderHeaderFilePath]
    ,[OrderDetailsFilePath]
    ,[ProcessInboundData]
    ,[ProcessInventoryData]
    ,[ProcessOutboundData])
VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?);