INSERT INTO [OutputTables_Dev].[DailyOrderProfileByVelocity] ([ProjectNumber_Velocity]
      ,[AvgDailySKUs]
      ,[AvgDailyOrders]
      ,[AvgDailyLines]
      ,[AvgDailyUnits]
      ,[DailySKUsSD]
      ,[DailyOrdersSD]
      ,[DailyLinesSD]
      ,[DailyUnitsSD]
      ,[ActiveSKUs]
      ,[OnHandSKUs]
      ,[QtyOnHand]
      ,[Plus1StDevSKUs]
      ,[Plus1StDevOrders]
      ,[Plus1StDevLines]
      ,[Plus1StDevUnits])
VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?);