UPDATE [OutputTables_Prod].[Project]
SET [Company] = ? 
    ,[Salesperson] = ?
    ,[CompanyLocation] = ?
    ,[ProjectName] = ?
    ,[Email] = ?
    ,[StartDate] = ?
    ,[DateForAnalysis] = ?
    ,[WeekendDateRule] = ?
    ,[Notes] = ?
    ,[DataUploaded] = ?
    ,[UploadDate] = ?
    ,[ItemMasterFilePath] = ?
    ,[InboundHeaderFilePath] = ?
    ,[InboundDetailsFilePath] = ?
    ,[InventoryFilePath] = ?
    ,[OrderHeaderFilePath] = ?
    ,[OrderDetailsFilePath] = ?
    ,[ProcessInboundData] = ?
    ,[ProcessInventoryData] = ?
    ,[ProcessOutboundData] = ?
WHERE [ProjectNumber] = ?