SELECT [SKU]
    ,[SKUDescription]
    ,[SKUClass]
    ,[Subwarehouse]
    ,[UnitOfMeasure]
    ,[Velocity]
    ,[InnerQuantity]
    ,[CartonQuantity]
    ,[CartonsPerPallet]
    ,[PalletTie]
    ,[PalletHigh]
    ,[MaxPalletStack]
    ,[EachLength]
    ,[EachWidth]
    ,[EachHeight]
    ,[EachWeight]
    ,[InnerLength]
    ,[InnerWidth]
    ,[InnerHeight]
    ,[InnerWeight]
    ,[CartonLength]
    ,[CartonWidth]
    ,[CartonHeight]
    ,[CartonWeight]
    ,[PalletLength]
    ,[PalletWidth]
    ,[PalletHeight]
    ,[PalletWeight] 
FROM [OutputTables_Dev].[ItemMaster] 
WHERE [ProjectNumber] = ?