SELECT [ProjectNumber]
      ,[Company]
      ,[Salesperson]
      ,[CompanyLocation]
      ,[ProjectName]
      ,[Email]
      ,[StartDate]
      ,[DateForAnalysis]
      ,[WeekendDateRule]
      ,[Notes]
      ,[DataUploaded]
      ,[UploadDate]
      ,[ItemMasterFilePath]
      ,[InboundHeaderFilePath]
      ,[InboundDetailsFilePath]
      ,[InventoryFilePath]
      ,[OrderHeaderFilePath]
      ,[OrderDetailsFilePath]
      ,[ProcessInboundData]
      ,[ProcessInventoryData]
      ,[ProcessOutboundData]
FROM [OutputTables_Dev].[Project]
WHERE [ProjectNumber] = ?